### ISSUE TITLE
Text on usernames clicked in chat is dark when using dark theme

### ISSUE THREAD

**Issue by gitgizmo7** [catppuccin/twitch#1]
Usernames are white when using default Twitch dark theme. Dark usernames result in readability issues.

<img width="331" alt="Screenshot 2023-02-07 at 3 50 53 PM" src="https://user-images.githubusercontent.com/93722725/217363293-9aa75d0b-fd06-483d-9efe-75d42060aee1.png">
<img width="333" alt="Screenshot 2023-02-07 at 3 51 36 PM" src="https://user-images.githubusercontent.com/93722725/217363307-1d75c590-c743-46b6-b1dc-fe46a4ce3702.png">

**Comment by mustafa-archived** [comment]
Fixed it https://github.com/catppuccin/twitch/commit/fd3b2110f9d6b1d41a14ae269ed68b7d42c7f4e6

**Comment by mustafa-archived** [comment]
https://github.com/catppuccin/twitch/commit/835eb6a8588a9344d6064a6312f098ded1f21b2f
