### ISSUE TITLE
Black text on channel points rewards and stream title/view counter in theatre mode

### ISSUE THREAD

**Issue by Gabri-kun** [catppuccin/twitch#10]
The points text in the channel points rewards menu has Black text while using the dark theme:

<img width="240" alt="twitch_points_catppuccin" src="https://user-images.githubusercontent.com/43643360/234052187-c08144ba-846b-43e7-b955-bcabe0c1ca1b.png">

The channel points text should be white like this:

<img width="242" alt="twitch_points" src="https://user-images.githubusercontent.com/43643360/234051408-506560a3-7e94-48e8-9a08-200663d02283.png">

Also the stream title/view counter on the top left in theatre mode should be adjusted.
This is how it looks:

<img width="305" alt="twitch_theatre_catppuccin" src="https://user-images.githubusercontent.com/43643360/234052590-dbffc677-87d9-46a8-b1ef-2375f2ccfc23.png">

Instead, it should look like this:

<img width="302" alt="twitch_theatre" src="https://user-images.githubusercontent.com/43643360/234052878-7b77f4ad-130b-49cb-a1bf-327e47f77892.png">

**Comment by mustafa-archived** [comment]
Fixed
