### ISSUE TITLE
Bar appears on right side of player in channels with overlay extensions

### ISSUE THREAD

**Issue by quiet-bear** [catppuccin/twitch#3]
There's a solid bar that appears on the right side of the player on channels that have overlay extensions enabled.

![no-bar](https://user-images.githubusercontent.com/65508804/218216121-8a825987-672a-4501-8596-e9e3bd27c2cd.png)
![bar](https://user-images.githubusercontent.com/65508804/218216160-100dacd8-805c-4033-ac48-ade6fa5efa47.png)

**Comment by mustafa-archived** [comment]
Fixed https://github.com/catppuccin/twitch/commit/bf45bebd8e0e5100da23c90f216a96e1a192eda1

Will have to change some text color later as well
