### ISSUE TITLE
Live viewer icon and text unexpected color

### ISSUE THREAD

**Issue by PPHyperion** [catppuccin/twitch#8]
The color of the live viewer icon and the text beside it is not as expected.

![styled](https://user-images.githubusercontent.com/38666687/233842167-898ded89-3a79-4d1d-a44f-fa95e459b0ce.png)

I would expect the icon and the number of viewers to be colored red, like it is in the original site.

![default](https://user-images.githubusercontent.com/38666687/233842233-b653d3fa-a2b9-4f70-a704-104e2a1432d0.png)

Is it intended this way?

**Comment by mustafa-archived** [comment]
Probably not, I'll fix it soon

**Comment by mustafa-archived** [comment]
Fixed https://github.com/catppuccin/twitch/commit/3bd095109ad09fd91de710ec717180fcf264241d
